### ISSUE TITLE
Script crashes with "No such file 'curl-config'"

### ISSUE THREAD

**Issue by MrPySmart** [defjaf/pip_upgrade_outdated#11]
Trying to use pip_upgrade_outdated on debian buster the script crashes.

Never worked with curl. Have I to meet any preconditions?

```
python3 -m pip_upgrade_outdated --version
__main__.py 1.5
```

```
>~$ python3 -m pip_upgrade_outdated -v
[{"name": "asn1crypto", "version": "0.24.0", "latest_version": "1.3.0", "latest_filetype": "wheel"}, {"name": "astroid", "version": "2.3.1", "latest_version": "2.4.1", "latest_filetype": "wheel"}, {"name": "certifi", "version": "2018.8.24", "latest_version": "2020.4.5.1", "latest_filetype": "wheel"}, {"name": "cffi", "version": "1.13.2", "latest_version": "1.14.0", "latest_filetype": "wheel"}, {"name": "cryptography", "version": "2.6.1", "latest_version": "2.9.2", "latest_filetype": "wheel"}, {"name": "distro", "version": "1.3.0", "latest_version": "1.5.0", "latest_filetype": "wheel"}, {"name": "gitdb2", "version": "2.0.6", "latest_version": "4.0.2", "latest_filetype": "wheel"}, {"name": "GitPython", "version": "3.0.4", "latest_version": "3.1.2", "latest_filetype": "wheel"}, {"name": "idna", "version": "2.6", "latest_version": "2.9", "latest_filetype": "wheel"}, {"name": "keyring", "version": "17.1.1", "latest_version": "21.2.1", "latest_filetype": "wheel"}, {"name": "keyrings.alt", "version": "3.1.1", "latest_version": "3.4.0", "latest_filetype": "wheel"}, {"name": "lazy-object-proxy", "version": "1.4.2", "latest_version": "1.4.3", "latest_filetype": "wheel"}, {"name": "Mako", "version": "1.0.7", "latest_version": "1.1.2", "latest_filetype": "wheel"}, {"name": "MarkupSafe", "version": "1.1.0", "latest_version": "1.1.1", "latest_filetype": "wheel"}, {"name": "numpy", "version": "1.17.4", "latest_version": "1.18.4", "latest_filetype": "wheel"}, {"name": "paramiko", "version": "2.6.0", "latest_version": "2.7.1", "latest_filetype": "wheel"}, {"name": "pick", "version": "0.6.4", "latest_version": "0.6.7", "latest_filetype": "wheel"}, {"name": "protobuf", "version": "3.9.2", "latest_version": "3.11.3", "latest_filetype": "wheel"}, {"name": "pycairo", "version": "1.16.2", "latest_version": "1.19.1", "latest_filetype": "sdist"}, {"name": "pycparser", "version": "2.19", "latest_version": "2.20", "latest_filetype": "wheel"}, {"name": "pycups", "version": "1.9.73", "latest_version": "2.0.1", "latest_filetype": "sdist"}, {"name": "pycurl", "version": "7.43.0.2", "latest_version": "7.43.0.5", "latest_filetype": "sdist"}, {"name": "pydocstyle", "version": "4.0.1", "latest_version": "5.0.2", "latest_filetype": "wheel"}, {"name": "pyflakes", "version": "2.1.1", "latest_version": "2.2.0", "latest_filetype": "wheel"}, {"name": "PyGObject", "version": "3.30.4", "latest_version": "3.36.1", "latest_filetype": "sdist"}, {"name": "pylint", "version": "2.4.2", "latest_version": "2.5.2", "latest_filetype": "wheel"}, {"name": "PyQt5", "version": "5.13.1", "latest_version": "5.14.2", "latest_filetype": "wheel"}, {"name": "PyQt5-sip", "version": "4.19.19", "latest_version": "12.7.2", "latest_filetype": "wheel"}, {"name": "pysmbc", "version": "1.0.15.6", "latest_version": "1.0.21", "latest_filetype": "sdist"}, {"name": "python-dateutil", "version": "2.8.0", "latest_version": "2.8.1", "latest_filetype": "wheel"}, {"name": "python-gitlab", "version": "1.13.0", "latest_version": "2.2.0", "latest_filetype": "wheel"}, {"name": "PyVISA-py", "version": "0.3.1", "latest_version": "0.4.0", "latest_filetype": "wheel"}, {"name": "pyxdg", "version": "0.25", "latest_version": "0.26", "latest_filetype": "wheel"}, {"name": "regex", "version": "2019.11.1", "latest_version": "2020.5.7", "latest_filetype": "wheel"}, {"name": "requests", "version": "2.21.0", "latest_version": "2.23.0", "latest_filetype": "wheel"}, {"name": "rope", "version": "0.14.0", "latest_version": "0.17.0", "latest_filetype": "sdist"}, {"name": "SecretStorage", "version": "2.3.1", "latest_version": "3.1.2", "latest_filetype": "wheel"}, {"name": "setuptools", "version": "40.8.0", "latest_version": "46.1.3", "latest_filetype": "wheel"}, {"name": "six", "version": "1.12.0", "latest_version": "1.14.0", "latest_filetype": "wheel"}, {"name": "smmap2", "version": "2.0.5", "latest_version": "3.0.1", "latest_filetype": "wheel"}, {"name": "snowballstemmer", "version": "1.9.1", "latest_version": "2.0.0", "latest_filetype": "wheel"}, {"name": "typed-ast", "version": "1.4.0", "latest_version": "1.4.1", "latest_filetype": "wheel"}, {"name": "urllib3", "version": "1.24.1", "latest_version": "1.25.9", "latest_filetype": "wheel"}, {"name": "wheel", "version": "0.32.3", "latest_version": "0.34.2", "latest_filetype": "wheel"}, {"name": "wrapt", "version": "1.11.2", "latest_version": "1.12.1", "latest_filetype": "sdist"}]

asn1crypto: 1.3.0 (wheel)
astroid: 2.4.1 (wheel)
certifi: 2020.4.5.1 (wheel)
cffi: 1.14.0 (wheel)
cryptography: 2.9.2 (wheel)
distro: 1.5.0 (wheel)
gitdb2: 4.0.2 (wheel)
GitPython: 3.1.2 (wheel)
idna: 2.9 (wheel)
keyring: 21.2.1 (wheel)
keyrings.alt: 3.4.0 (wheel)
lazy-object-proxy: 1.4.3 (wheel)
Mako: 1.1.2 (wheel)
MarkupSafe: 1.1.1 (wheel)
numpy: 1.18.4 (wheel)
paramiko: 2.7.1 (wheel)
pick: 0.6.7 (wheel)
protobuf: 3.11.3 (wheel)
pycairo: 1.19.1 (sdist)
pycparser: 2.20 (wheel)
pycups: 2.0.1 (sdist)
pycurl: 7.43.0.5 (sdist)
pydocstyle: 5.0.2 (wheel)
pyflakes: 2.2.0 (wheel)
PyGObject: 3.36.1 (sdist)
pylint: 2.5.2 (wheel)
PyQt5: 5.14.2 (wheel)
PyQt5-sip: 12.7.2 (wheel)
pysmbc: 1.0.21 (sdist)
python-dateutil: 2.8.1 (wheel)
python-gitlab: 2.2.0 (wheel)
PyVISA-py: 0.4.0 (wheel)
pyxdg: 0.26 (wheel)
regex: 2020.5.7 (wheel)
requests: 2.23.0 (wheel)
rope: 0.17.0 (sdist)
SecretStorage: 3.1.2 (wheel)
setuptools: 46.1.3 (wheel)
six: 1.14.0 (wheel)
smmap2: 3.0.1 (wheel)
snowballstemmer: 2.0.0 (wheel)
typed-ast: 1.4.1 (wheel)
urllib3: 1.25.9 (wheel)
wheel: 0.34.2 (wheel)
wrapt: 1.12.1 (sdist)
Outdated packages:  ['asn1crypto', 'astroid', 'certifi', 'cffi', 'cryptography', 'distro', 'gitdb2', 'GitPython', 'idna', 'keyring', 'keyrings.alt', 'lazy-object-proxy', 'Mako', 'MarkupSafe', 'numpy', 'paramiko', 'pick', 'protobuf', 'pycairo', 'pycparser', 'pycups', 'pycurl', 'pydocstyle', 'pyflakes', 'PyGObject', 'pylint', 'PyQt5', 'PyQt5-sip', 'pysmbc', 'python-dateutil', 'python-gitlab', 'PyVISA-py', 'pyxdg', 'regex', 'requests', 'rope', 'SecretStorage', 'setuptools', 'six', 'smmap2', 'snowballstemmer', 'typed-ast', 'urllib3', 'wheel', 'wrapt']
Upgrade command:  pip install  --upgrade asn1crypto astroid certifi cffi cryptography distro gitdb2 GitPython idna keyring keyrings.alt lazy-object-proxy Mako MarkupSafe numpy paramiko pick protobuf pycairo pycparser pycups pycurl pydocstyle pyflakes PyGObject pylint PyQt5 PyQt5-sip pysmbc python-dateutil python-gitlab PyVISA-py pyxdg regex requests rope SecretStorage setuptools six smmap2 snowballstemmer typed-ast urllib3 wheel wrapt
Error:     ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-o8eahsm0/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-o8eahsm0/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ov0d96v3
         cwd: /tmp/pip-install-o8eahsm0/pycurl/
    Complete output (22 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-o8eahsm0/pycurl/setup.py", line 234, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o8eahsm0/pycurl/setup.py", line 961, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-o8eahsm0/pycurl/setup.py", line 623, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-o8eahsm0/pycurl/setup.py", line 101, in __init__
        self.configure()
      File "/tmp/pip-install-o8eahsm0/pycurl/setup.py", line 238, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Defaulting to user installation because normal site-packages is not writeable
Collecting asn1crypto
  Using cached asn1crypto-1.3.0-py2.py3-none-any.whl (103 kB)
Collecting astroid
  Using cached astroid-2.4.1-py3-none-any.whl (214 kB)
Collecting certifi
  Using cached certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
Collecting cffi
  Using cached cffi-1.14.0-cp37-cp37m-manylinux1_x86_64.whl (400 kB)
Collecting cryptography
  Using cached cryptography-2.9.2-cp35-abi3-manylinux2010_x86_64.whl (2.7 MB)
Collecting distro
  Using cached distro-1.5.0-py2.py3-none-any.whl (18 kB)
Collecting gitdb2
  Using cached gitdb2-4.0.2-py3-none-any.whl (1.1 kB)
Collecting GitPython
  Using cached GitPython-3.1.2-py3-none-any.whl (451 kB)
Collecting idna
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting keyring
  Using cached keyring-21.2.1-py3-none-any.whl (31 kB)
Collecting keyrings.alt
  Using cached keyrings.alt-3.4.0-py2.py3-none-any.whl (31 kB)
Collecting lazy-object-proxy
  Using cached lazy_object_proxy-1.4.3-cp37-cp37m-manylinux1_x86_64.whl (56 kB)
Collecting Mako
  Using cached Mako-1.1.2-py2.py3-none-any.whl (75 kB)
Collecting MarkupSafe
  Using cached MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl (27 kB)
Collecting numpy
  Using cached numpy-1.18.4-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
Collecting paramiko
  Using cached paramiko-2.7.1-py2.py3-none-any.whl (206 kB)
Collecting pick
  Using cached pick-0.6.7-py2.py3-none-any.whl (5.5 kB)
Collecting protobuf
  Using cached protobuf-3.11.3-cp37-cp37m-manylinux1_x86_64.whl (1.3 MB)
Collecting pycairo
  Using cached pycairo-1.19.1.tar.gz (205 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pycups
  Using cached pycups-2.0.1.tar.gz (62 kB)
Collecting pycurl
  Using cached pycurl-7.43.0.5.tar.gz (216 kB)
```

**Comment by MrPySmart** [comment]
O.K. I it seems that the script crashes for all outdated packages of type **sdist**.
As some linux packages are not present to built this python packages locally prior to upating them.
After installing them on linux it is (manually) possible to update the python packages - have not tried to update them by pip_upgrade_outdated.

Nevertheless: The pip_upgrade_outdated should go on with the next outdated package and do not stop.

**Comment by defjaf** [comment]
Reasonable request. I’ll see what I can do — probably not too soon, however...

**Comment by defjaf** [comment]
I now realise that running it the usual way, where it uses a single `pip` command for all the packages, will always fail this way if it fails for any of the packages (I think).

So you may want to try the `--sequential` flag, which runs separate `pip` commands for each package. Not sure how it will deal with failures, but in any event I think the fix would have to be running in this mode.

**Comment by MrPySmart** [comment]
O.K. retested right now.
A lot of packages were outdated and with the --sequential flag everything worked well. Thank You!
