### ISSUE TITLE
Crashes with pip 8.1.2

### ISSUE THREAD

**Issue by hartwork** [defjaf/pip_upgrade_outdated#2]
This is on CentOS 7. In detail:

```console
$ pip_upgrade_outdated --version
pip_upgrade_outdated 1.2

$ pip --version
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)

$ sudo pip_upgrade_outdated
Error: 
Usage:   
  pip list [options]

no such option: --format

Traceback (most recent call last):
  File "/bin/pip_upgrade_outdated", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/pip_upgrade_outdated/upgrade_pip_packages.py", line 125, in main
    packages = collect_packages(pip_cmd=pip_cmd, verbose=args.verbose)
  File "/usr/lib/python2.7/site-packages/pip_upgrade_outdated/upgrade_pip_packages.py", line 83, in collect_packages
    pkgs = json.loads(stdout.decode())
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by hartwork** [comment]
Idea: First check pip version, upgrade `pip` (and `setuptools`) as needed, maybe install `wheel` even, continue as usual.
