### ISSUE TITLE
Failing during updating pip

### ISSUE THREAD

**Issue by 07pepa** [defjaf/pip_upgrade_outdated#9]
when uprgrading pip it fails ...
(probably because pip is in use)

it is recomended to upgrade pip with 
```cmd
python -m pip install --upgrade pip
```
so if you detect pip as outdated update it with this comand

that should fix it

**Comment by defjaf** [comment]
I have never seen this behaviour. 

Can you give more information about the setup (OS, python version, distribution, etc) and the error message?

**Comment by 07pepa** [comment]
well OS is win10 python 3.7 (and seen in 3.8) distro.... window 10 err mesage... i will copy exact message but what i recal it was  going out of pip itself  maybe try update pip on windows? 

when i reproduce  this again i will attach msg

**Comment by defjaf** [comment]
Yes, please do. You can always explicitly downgrade and then try to run it again, if you want to test it.

**Comment by 07pepa** [comment]
I did clean install of python and i reprocuded it  ( icluding repro steps)


## Steps to reprocude  from clean state

1) clean install of python 3 (3.8) (if reinstaling do not forget to clean C:\Program Files from python dirs like `C:\Program Files\PythonXX`  where XX are numbers)
2) run any shell with admin priv ( i used powershell)

### in shell:
1) pip install pip-upgrade-outdated  ( must issue warning that pip is old and we should update via comand `python -m pip install --upgrade pip`)
2) pip_upgrade_outdated  ( also happen with exe)
3) UnicodeDecodeError exeption thrown
4) nothing after pip is updated

however pip updates (updating pip from 19.2.3 to  19.3.1)

in my case setup tools supoosed to be updated also but exeption iterupted it

### TRACEBACK
```
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\pip_upgrade_outdated.exe\__main__.py", line 9, in <module>
  File "c:\program files\python38\lib\site-packages\pip_upgrade_outdated\upgrade_pip_packages.py", line 183, in main
    upgrade_package(all_packages, pip_cmd=pip_cmd, pip_args=pip_args, verbose=args.verbose,
  File "c:\program files\python38\lib\site-packages\pip_upgrade_outdated\upgrade_pip_packages.py", line 68, in upgrade_package
    print("Error:", stderr.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 76: invalid start byte
```
